### ISSUE TITLE
Paynl GraphQL v2.0.0 support

### ISSUE THREAD

**Issue by indykoning** [rapidez/paynl#8]
https://github.com/paynl/magento2-graphql/releases/tag/v2.0.0
came out with the folowing relevant changes

 - Retrieve issuerURL through placeOrder (replaces paynlTransactionStart)

Removed:
 - paynlStartTransaction
 - paynlFinishTransaction
 - paynlGetPayLink

**Comment by royduin** [comment]
Fixed: https://github.com/rapidez/paynl/pull/14
